name: CI


# Trigger in two scenarios:
# 1) when pushing directly into master, and
# 2) when pull requests are opened on devel
on:
  push:
    branches: [master]

  pull_request:
    branches: [devel]

  workflow_dispatch:


jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install gfortran libopenblas-dev libopenmpi-dev
        echo Finish GFORTRAN install

    - name: Configure and Compile
      run: |
        mkdir build
        cmake -S . -B build
        cmake --build build -j 8
