name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        sudo apt-get install gfortran
        echo Finish GFORTRAN install
        export FEAPPVHOME5_1=`pwd`
        echo set envrionment variable
        echo $FEAPPVHOME5_1
        make install
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
